apiVersion: batch/v1
kind: Job
metadata:
  name: trainer
spec:
  template:
    metadata:
      name: trainer
      labels:
        k8s-app: trainer
    spec:
      serviceAccountName: maestro
      containers:
      - name: trainer
        image: ghcr.io/ucsd-e4e/maestro_trainer:main
        env:
        - name: pod-name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SERVER_URL
          value: https://test-service2.nrp-nautilus.io
        volumeMounts:
          - name: data-pvc
            mountPath: /data/
        resources:
        resources:
          limits:
            memory: 24Gi
            cpu: "12"
            nvidia.com/gpu: 1
          requests:
            memory: 24Gi
            cpu: "12"
            nvidia.com/gpu: 1
      restartPolicy: Never
      imagePullSecrets:
        - name: regcred
      volumes:
      - name: data-pvc
        persistentVolumeClaim:
          claimName: data-pvc