apiVersion: batch/v1
kind: Job
metadata:
  name: trainer
spec:
  template:
    metadata:
      name: trainer
      labels:
        k8s-app: trainer
    spec:
      serviceAccountName: maestro
      containers:
      - name: trainer
        image: gitlab-registry.nrp-nautilus.io/model-maestro/model_trainer:latest
        env:
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
        volumeMounts:
          - name: data-pvc
            mountPath: /data/
        resources:
          limits:
            memory: 10Gi
            cpu: "1"
          requests:
            memory: 10Gi
            cpu: "1"
      restartPolicy: Never
      imagePullSecrets:
        - name: regcred
      volumes:
      - name: data-pvc
        persistentVolumeClaim:
          claimName: data-pvc