apiVersion: batch/v1
kind: Job
metadata:
  name: test-schuduler-job
spec:
  template:
    metadata:
      name: test-schuduler-job
    spec:
      containers:
      - name: test-schuduler-job
        image: siloux/test_job_process:latest
        resources:
          limits:
            memory: 1Gi
            cpu: "1"
          requests:
            memory: 1Gi
            cpu: "1"
      restartPolicy: Never